### ISSUE TITLE
entering 0 for minimum word occurrence rate during vsm prep causes error

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#102]
Enter the minimum word occurrence rate: 0
Traceback (most recent call last):
  File "/Users/colin/anaconda/bin/vsm", line 9, in <module>
    load_entry_point('topicexplorer==1.0b47', 'console_scripts', 'vsm')()
  File "/Users/colin/corpora/topicexplorer/topicexplorer/__main__.py", line 83, in main
    prep.main(args)
  File "/Users/colin/corpora/topicexplorer/topicexplorer/prep.py", line 294, in main
    low_filter, candidates = get_low_filter(args, c, words=stoplist)
  File "/Users/colin/corpora/topicexplorer/topicexplorer/prep.py", line 202, in get_low_filter
    candidates = get_candidate_words(c, -input_filter)
  File "/Users/colin/corpora/topicexplorer/topicexplorer/prep.py", line 79, in get_candidate_words
    mask = get_mask(c, words, filter=filter)
UnboundLocalError: local variable 'filter' referenced before assignment

**Comment by JaimieMurdock** [comment]
Fixed in master, `vsm update` on a dev install will have this update. Will roll into next release.
