### ISSUE TITLE
autocomplete search fails

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#110]
init/prep/train on these files and the resulting instance of TE does not have autocomplete-search functionality
[BJPS-txt 2.zip](https://github.com/inpho/topic-explorer/files/156913/BJPS-txt.2.zip)

**Comment by JaimieMurdock** [comment]
Unzipping the file on Windows yields
![image](https://cloud.githubusercontent.com/assets/666240/13582705/dbdb8d8c-e47b-11e5-9df3-38cf2953b90c.png)

**Comment by JaimieMurdock** [comment]
can't replicate on own machine

**Comment by colinallen** [comment]
just retrained with updated vsm and same problem, two different browsers.


On Mar 7, 2016, at 3:52 PM, Jaimie Murdock <notifications@github.com<mailto:notifications@github.com>> wrote:


can't replicate on own machine

**Comment by colinallen** [comment]
```
127.0.0.1 - - [08/Mar/2016 17:39:22] "GET /docs.json?q=195 HTTP/1.1" 500 754
Traceback (most recent call last):
  File "/Users/colin/anaconda/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Users/colin/anaconda/bin/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/Users/colin/corpora/topicexplorer/topicexplorer/server.py", line 35, in set_header
    return f(*args, **kwargs)
  File "/Users/colin/corpora/topicexplorer/topicexplorer/server.py", line 234, in docs
    js = get_docs(docs, query=q)
  File "/Users/colin/corpora/topicexplorer/topicexplorer/server.py", line 252, in get_docs
    if query is None or query.lower() in label(doc).lower():
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 48: ordinal not in range(128)
'''
