### ISSUE TITLE
can't use multi-process when train an exist model

### ISSUE THREAD

**Issue by luohongliang** [inpho/topic-explorer#222]
Hi Jaimie, 

When I try training an exist model ,using `topixexplorer train handian.ini -p 5`. It occurs an unsized object error. But when using ` `topixexplorer train handian.ini`, all goes well. 
Here is the details:

```
Loading LDA data from /home/inpho/inpho/kmx/models/kmx-freq5-freq5-N2523342-LDA-K20-document-4000.npz
Continue training 20-topic model (4000 => 6000 iterations)
Traceback (most recent call last):
  File "/home/inpho/anaconda2/bin/vsm", line 11, in <module>
    load_entry_point('topicexplorer', 'console_scripts', 'vsm')()
  File "/home/inpho/topicexplorer/topicexplorer/__main__.py", line 67, in vsm
    main()
  File "/home/inpho/topicexplorer/topicexplorer/__main__.py", line 231, in main
    benchmark(train.main)(args)
  File "/home/inpho/topicexplorer/topicexplorer/train.py", line 188, in main
    dry_run=args.dry_run)
  File "/home/inpho/topicexplorer/topicexplorer/train.py", line 67, in continue_training
    m.train(n_iterations=total_iterations - orig_iterations)
  File "/home/inpho/anaconda2/lib/python2.7/site-packages/vsm/model/ldacgsmulti.py", line 309, in train
    self._move_locals_to_globals()
  File "/home/inpho/anaconda2/lib/python2.7/site-packages/vsm/model/ldacgsmulti.py", line 132, in _move_locals_to_globals
    self.inv_top_sums = self.inv_top_sums
  File "/home/inpho/anaconda2/lib/python2.7/site-packages/vsm/model/ldacgsmulti.py", line 171, in inv_top_sums
    _inv_top_sums = mp.Array('f', self.K, lock=False)
  File "/home/inpho/anaconda2/lib/python2.7/multiprocessing/__init__.py", line 260, in Array
    return Array(typecode_or_type, size_or_initializer, **kwds)
  File "/home/inpho/anaconda2/lib/python2.7/multiprocessing/sharedctypes.py", line 120, in Array
    obj = RawArray(typecode_or_type, size_or_initializer)
  File "/home/inpho/anaconda2/lib/python2.7/multiprocessing/sharedctypes.py", line 92, in RawArray
    type_ = type_ * len(size_or_initializer)
TypeError: len() of unsized object
```

**Comment by JaimieMurdock** [comment]
It should automatically load the same number of parallel instances. Changing the number of instances will change the model results, as each process continues from its own random state. Was the original model trained with multiprocessing?

**Comment by luohongliang** [comment]
Yes,Multiprocessing. Even all models are using with the same number of proccessors.
Did you meet the same problem while retraining?
