### ISSUE TITLE
can't retrain model at third time

### ISSUE THREAD

**Issue by luohongliang** [inpho/topic-explorer#223]
Hi Jaimie,

I trained a model for 500 iterations. Then retrained it to 750 iterations. Then when I try retraining it for 1000 times. It occurs an error.

```
Loading LDA data from /home/inpho/inpho/kmx2/models/kmx-freq5-freq5-N234234-LDA-K20-document-750.npz
Loading LDA data from /home/inpho/inpho/kmx2/models/kmx-freq5-freq5-N234234-LDA-K20-document-750.npz
Continue training 20-topic model (750 => 1125 iterations)
Traceback (most recent call last):
  File "/home/inpho/anaconda2/bin/topicexplorer", line 11, in <module>
    load_entry_point('topicexplorer', 'console_scripts', 'topicexplorer')()
  File "/home/inpho/topicexplorer/topicexplorer/__main__.py", line 231, in main
    benchmark(train.main)(args)
  File "/home/inpho/topicexplorer/topicexplorer/train.py", line 188, in main
    dry_run=args.dry_run)
  File "/home/inpho/topicexplorer/topicexplorer/train.py", line 67, in continue_training
    m.train(n_iterations=total_iterations - orig_iterations)
  File "/home/inpho/anaconda2/lib/python2.7/site-packages/vsm/model/ldacgsseq.py", line 184, in train
    self.corpus.dtype, self.Ktype))
NotImplementedError: Unsupported corpus dtype (uint16) and topic dtype (<type 'numpy.uint8'>) combination
```

But, when I changed the model path in .ini file back to 500. `model_pattern = /home/inpho/inpho/kmx2/models/kmx-freq5-freq5-N2523342-LDA-K{0}-document-500.npz`. It can retrain again.
So ,if there is any problem with the 750 iteration model?

Please have look.
Regards,

Hongliang

**Comment by JaimieMurdock** [comment]
Seems like the corpus dtype and topic dtypes changed, which is super strange because they should remain constant.

Will add a test case to the unit tests and attempt to debug.

**Comment by JaimieMurdock** [comment]
I can replicate now, trying to fix!

**Comment by JaimieMurdock** [comment]
So the error is completely related to #222. The continue training is not using the same number of processes, as it should.

```
topicexplorer train ap -k 20 40 60 80 100 --iter 50 -p 3 --rebuild
topicexplorer train ap -k 20 40 60 80 100 --iter 80 --continue
```

**Comment by JaimieMurdock** [comment]
So the issue here, I think - is that we first train a model using the single-threaded version then on second load train it using the multithreaded one.

**Comment by luohongliang** [comment]
With the command:
`
topicexplorer train ap -k 20 40 60 80 100 --iter 50 -p 3 --rebuild
`
`
topicexplorer train ap -k 20 40 60 80 100 --iter 80 --continue
`
it can only work at the first model, which is k =20 model. 
However,  when k goes to 40, the TypeError: len() of unsized object occurs again.

```
inpho@inpho-W560-G20:~/inpho/kmx2$ topicexplorer train kmx -k 40 60 80 100 --iter 670 --continue
kmx is a directory, using the config file kmx.ini
Loading corpus... 
Loading LDA data from /home/inpho/inpho/kmx2/models/kmx-freq5-freq5-N3546346-LDA-K40-document-500.npz
Loading LDA data from /home/inpho/inpho/kmx2/models/kmx-freq5-freq5-N3546346-LDA-K40-document-500.npz
Continue training 40-topic model (500 => 670 iterations, 10 processes)
Begin LDA training for 170 iterations
100%|##########################################################################|
Saving LDA model to /home/inpho/inpho/kmx2/models/kmx-freq5-freq5-N3546346-LDA-K40-document-670.npz
Loading LDA data from /home/inpho/inpho/kmx2/models/kmx-freq5-freq5-N3546346-LDA-K80-document-500.npz
Continue training 80-topic model (500 => 670 iterations, 10 processes)
Traceback (most recent call last):
  File "/home/inpho/anaconda2/bin/topicexplorer", line 11, in <module>
    load_entry_point('topicexplorer', 'console_scripts', 'topicexplorer')()
  File "/home/inpho/topicexplorer/topicexplorer/__main__.py", line 231, in main
    benchmark(train.main)(args)
  File "/home/inpho/topicexplorer/topicexplorer/train.py", line 187, in main
    dry_run=args.dry_run)
  File "/home/inpho/topicexplorer/topicexplorer/train.py", line 71, in continue_training
    m.train(n_iterations=total_iterations - orig_iterations)
  File "/home/inpho/anaconda2/lib/python2.7/site-packages/vsm/model/ldacgsmulti.py", line 309, in train
    self._move_locals_to_globals()
  File "/home/inpho/anaconda2/lib/python2.7/site-packages/vsm/model/ldacgsmulti.py", line 132, in _move_locals_to_globals
    self.inv_top_sums = self.inv_top_sums
  File "/home/inpho/anaconda2/lib/python2.7/site-packages/vsm/model/ldacgsmulti.py", line 171, in inv_top_sums
    _inv_top_sums = mp.Array('f', self.K, lock=False)
  File "/home/inpho/anaconda2/lib/python2.7/multiprocessing/__init__.py", line 260, in Array
    return Array(typecode_or_type, size_or_initializer, **kwds)
  File "/home/inpho/anaconda2/lib/python2.7/multiprocessing/sharedctypes.py", line 120, in Array
    obj = RawArray(typecode_or_type, size_or_initializer)
  File "/home/inpho/anaconda2/lib/python2.7/multiprocessing/sharedctypes.py", line 92, in RawArray
    type_ = type_ * len(size_or_initializer)
TypeError: len() of unsized object
```

**Comment by luohongliang** [comment]
So now I can retrain the model one by one , with command`topicexplorer train kmx -k 20 --iter 670 --continue`
As shown in command, --continue will train for 170 iterations, from 500 to 670.
But when I try to retrain the model for 1000 iterations at third time. It still start from 500 not 670. Is that the right way to retrain?
When I modified .ini file model path to 670 iteration model `model_pattern = /home/inpho/inpho/kmx2/models/kmx-freq5-freq5-N3546346-LDA-K{0}-document-670.npz`, it will goes error.
```
Traceback (most recent call last):
  File "/home/inpho/anaconda2/bin/topicexplorer", line 11, in <module>
    load_entry_point('topicexplorer', 'console_scripts', 'topicexplorer')()
  File "/home/inpho/topicexplorer/topicexplorer/__main__.py", line 231, in main
    benchmark(train.main)(args)
  File "/home/inpho/topicexplorer/topicexplorer/train.py", line 192, in main
    dry_run=args.dry_run)
  File "/home/inpho/topicexplorer/topicexplorer/train.py", line 71, in continue_training
    m.train(n_iterations=total_iterations - orig_iterations)
  File "/home/inpho/anaconda2/lib/python2.7/site-packages/vsm/model/ldacgsseq.py", line 184, in train
    self.corpus.dtype, self.Ktype))
NotImplementedError: Unsupported corpus dtype (uint16) and topic dtype (<type 'numpy.uint8'>) combination

```

**Comment by JaimieMurdock** [comment]
Very strange - it should go a third time, because that's how the test case
works. This is on a linux computer?

**Comment by luohongliang** [comment]
Yes,  Ubuntu 14.04 with the version 1.0b185-1-ga80a205-dirty.
Or it is the chinese corpus problem? Could you please try my corpus on your mechine? 
I push it to [github](https://github.com/luohongliang/kmx). The kmx folder contains all the txt files.

**Comment by JaimieMurdock** [comment]
I've been reviewing this bug today, @luohongliang and already encountered an error in Chinese tokenizer:
`topicexplorer init kmx --rebuild --tokenizer zh --name "KMX"`

```
Traceback (most recent call last):
  File "/home/jaimie/anaconda3/envs/py27/bin/topicexplorer", line 10, in <module>
    sys.exit(main())
  File "/home/jaimie/workspace/inpho/topic-explorer/topicexplorer/__main__.py", line 223, in main
    args.config_file = benchmark(init.main)(args)
  File "/home/jaimie/workspace/inpho/topic-explorer/topicexplorer/init.py", line 298, in main
    sentences=args.sentences, tokenizer=args.tokenizer)
  File "/home/jaimie/workspace/inpho/topic-explorer/topicexplorer/init.py", line 186, in build_corpus
    from topicexplorer.lib.chinese import modern_chinese_tokenizer
  File "/home/jaimie/workspace/inpho/topic-explorer/topicexplorer/lib/chinese.py", line 73, in <module>
    chinese_punctuation.append(chr(n+65280).decode('utf-8'))
ValueError: chr() arg not in range(256)
```

Some pervasive unicode issues.

**Comment by JaimieMurdock** [comment]
This was the issue: http://python-future.org/compatible_idioms.html#unichr

**Comment by JaimieMurdock** [comment]
Was able to successfully train 3 times:

```
topicexplorer init kmx --rebuild --tokenizer zh --name "kmx" -q
topicexplorer prep kmx --high-percent 30 --low-percent 20 -q
topicexplorer train kmx -k 20 40 --iter 20 -q
topicexplorer train kmx -k 20 40 --continue --iter 30 -q
topicexplorer train kmx -k 20 40 --continue --iter 45 -q
```
Closing issue.
