### ISSUE TITLE
not 'str' error on first load of support files

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#230]
Running locally, on MacOS, errors such as the following occur each time a new resource file is loaded for the first time (e.g. css, csv, js):

Traceback (most recent call last):
TypeError: a bytes-like object is required, not 'str'
  File "/Users/colin/anaconda3/lib/python3.6/site-packages/paste/httpserver.py", line 1085, in process_request_in_thread
    self.finish_request(request, client_address)
----------------------------------------
  File "/Users/colin/anaconda3/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/colin/anaconda3/lib/python3.6/socketserver.py", line 696, in __init__
    self.handle()
  File "/Users/colin/anaconda3/lib/python3.6/site-packages/paste/httpserver.py", line 459, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/Users/colin/anaconda3/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/Users/colin/anaconda3/lib/python3.6/site-packages/paste/httpserver.py", line 454, in handle_one_request
    self.wsgi_execute()
  File "/Users/colin/anaconda3/lib/python3.6/site-packages/paste/httpserver.py", line 309, in wsgi_execute
    self.wsgi_write_chunk('')
  File "/Users/colin/anaconda3/lib/python3.6/site-packages/paste/httpserver.py", line 167, in wsgi_write_chunk
    self.wfile.write(chunk)
  File "/Users/colin/anaconda3/lib/python3.6/socketserver.py", line 775, in write
    self._sock.sendall(b)
TypeError: a bytes-like object is required, not 'str'
----------------------------------------

**Comment by JaimieMurdock** [comment]
This is due to the new Python 3 str/bytes distinction - are there end user consequences? and is it only on static files?

**Comment by colinallen** [comment]
I don't think there are any end-user consequences, and I've only seen it on static files, so label this more a nuisance than a bug.

**Comment by JaimieMurdock** [comment]
I've seen this issue before, but for some reason can't replicate now

**Comment by JaimieMurdock** [comment]
Can you send the server logs with a 500 status error code so I know which page to request to raise the error?

**Comment by JaimieMurdock** [comment]
This  is an issue upstream in paste: https://bitbucket.org/ianb/paste/issues/17/httpserverpy-python-3

I've switched the built-in server to use waitress instead, and logging happens through paste's TransLogger module - so same functionality, hopefully more robustness. Will go live in next version to PyPI.
