### ISSUE TITLE
topicexplorer bad arg

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#238]
command line 'topicexplorer foo' for any unrecognized argument 'foo' returns an ugly error message:

>  Traceback (most recent call last):
>  File "/Users/colin/anaconda/lib/python3.6/site-packages/topicexplorer/__main__.py", line 164, in main
>    profile = new_args.index('-p')
> ValueError: '-p' is not in list

It should simply report that 'foo' is not a recognized argument and print the help message.

**Comment by colinallen** [comment]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/colin/anaconda/bin/topicexplorer", line 11, in <module>
    load_entry_point('topicexplorer==1.0b191', 'console_scripts', 'topicexplorer')()
  File "/Users/colin/anaconda/lib/python3.6/site-packages/topicexplorer/__main__.py", line 189, in main
    ArgumentParser.error(parser, e.message)
AttributeError: 'ArgumentParserError' object has no attribute 'message'

**Comment by colinallen** [comment]
Also, input could be compared via edit distance to legitimate commands, and suggest correction

**Comment by colinallen** [comment]
This appears to be only a problem in the Python 3 version

**Comment by colinallen** [comment]
Closing for now -- this seems to be a local issue on my laptop only.
