### ISSUE TITLE
Error in `topicexplroer prep` with comparison of args

### ISSUE THREAD

**Issue by JaimieMurdock** [inpho/topic-explorer#251]
![image](https://user-images.githubusercontent.com/666240/35937593-acfec318-0c14-11e8-88db-56f9411d1e7c.png)

**Comment by JaimieMurdock** [comment]
```
topicexplorer blurg
Traceback (most recent call last):
  File "/Users/colin/topicexplorer/topicexplorer/__main__.py", line 171, in main
    profile = new_args.index('-p')
ValueError: '-p' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/colin/topicexplorer/topicexplorer/__main__.py", line 180, in main
    raise e
  File "/Users/colin/topicexplorer/topicexplorer/__main__.py", line 164, in main
    args = parser.parse_args()
  File "/Users/colin/anaconda3/lib/python3.6/argparse.py", line 1730, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Users/colin/anaconda3/lib/python3.6/argparse.py", line 1769, in parse_known_args
    self.error(str(err))
  File "/Users/colin/topicexplorer/topicexplorer/__main__.py", line 54, in error
    raise ArgumentParserError(message)
topicexplorer.__main__.ArgumentParserError: argument {version,demo,update,init,prep,train,launch,notebook,metadata}: invalid choice: 'blurg' (choose from 'version', 'init', 'prep', 'train', 'launch', 'serve', 'notebook', 'demo', 'update', 'metadata', 'export', 'import')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/colin/anaconda3/bin/topicexplorer", line 11, in <module>
    load_entry_point('topicexplorer', 'console_scripts', 'topicexplorer')()
  File "/Users/colin/topicexplorer/topicexplorer/__main__.py", line 196, in main
    ArgumentParser.error(parser, e.message)
AttributeError: 'ArgumentParserError' object has no attribute 'message'
```
