### ISSUE TITLE
update fail

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#261]
```You have an editable install, so updates will be pulled from git.
Your install directory is: /Users/colin/topicexplorer

Your branch is 68 commits behind GitHub.
Pulling changes.
Download error on https://pypi.python.org/simple/pbr/: [Errno 22] Invalid argument -- Some packages may not be found!
Couldn't find index page for 'pbr' (maybe misspelled?)
Download error on https://pypi.python.org/simple/: [Errno 22] Invalid argument -- Some packages may not be found!
No local packages or working download links found for pbr
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    tests_require=['unittest2']
  File "/Users/colin/anaconda3/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/Users/colin/anaconda3/lib/python3.6/site-packages/setuptools/dist.py", line 335, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/Users/colin/anaconda3/lib/python3.6/site-packages/setuptools/dist.py", line 456, in fetch_build_eggs
    replace_conflicting=True,
  File "/Users/colin/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 863, in resolve
    replace_conflicting=replace_conflicting
  File "/Users/colin/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1141, in best_match
    return self.obtain(req, installer)
  File "/Users/colin/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1153, in obtain
    return installer(requirement)
  File "/Users/colin/anaconda3/lib/python3.6/site-packages/setuptools/dist.py", line 522, in fetch_build_egg
    return cmd.easy_install(req)
  File "/Users/colin/anaconda3/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 666, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pbr')
ERROR: Update did not comlete installation.

**Comment by colinallen** [comment]
This was due to IPv6 config error in Mac OS that was affecting address resolution. Solution was to change setting in System Preferences > Network > Advanced > TCP/IP > Configure IPv6 to "Link-local only" (from Automatic)
