### ISSUE TITLE
error on topicexporer update

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#292]
version 1.0b202-18-g6f6cb3a

```
% topicexplorer update
You have an editable install, so updates will be pulled from git.
Your install directory is: /Users/colin/corpora/topicexplorer

Traceback (most recent call last):
  File "/Users/colin/anaconda3/bin/topicexplorer", line 10, in <module>
    sys.exit(main())
  File "/Users/colin/corpora/topicexplorer/topicexplorer/__main__.py", line 260, in main
    benchmark(update.main)(args)
  File "/Users/colin/corpora/topicexplorer/topicexplorer/update.py", line 196, in main
    update(args)
  File "/Users/colin/corpora/topicexplorer/topicexplorer/update.py", line 111, in update
    if repo.active_branch != repo.heads.master:
  File "/Users/colin/anaconda3/lib/python3.6/site-packages/git/repo/base.py", line 267, in heads
    return Head.list_items(self)
  File "/Users/colin/anaconda3/lib/python3.6/site-packages/git/util.py", line 942, in list_items
    out_list.extend(cls.iter_items(repo, *args, **kwargs))
  File "/Users/colin/anaconda3/lib/python3.6/site-packages/git/refs/symbolic.py", line 609, in _iter_items
    for sha, rela_path in cls._iter_packed_refs(repo):  # @UnusedVariable
  File "/Users/colin/anaconda3/lib/python3.6/site-packages/git/refs/symbolic.py", line 100, in _iter_packed_refs
    raise TypeError("PackingType of packed-Refs not understood: %r" % line)
TypeError: PackingType of packed-Refs not understood: '# pack-refs with: peeled fully-peeled sorted'
```

**Comment by colinallen** [comment]
I verified that I still had the problem, backtracked to b201 and then reinstalled b202 which fixed the problem.  May be hard to diagnose if this can't be replicated.
