### ISSUE TITLE
Py3 problem when using Chinese tokenizer

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#298]
```Traceback (most recent call last):
  File "/Users/colin/anaconda/bin/topicexplorer", line 11, in <module>
    sys.exit(main())
  File "/Users/colin/anaconda/lib/python3.6/site-packages/topicexplorer/__main__.py", line 223, in main
    args.config_file = benchmark(init.main)(args)
  File "/Users/colin/anaconda/lib/python3.6/site-packages/topicexplorer/init.py", line 269, in main
    sentences=args.sentences, tokenizer=args.tokenizer)
  File "/Users/colin/anaconda/lib/python3.6/site-packages/topicexplorer/init.py", line 157, in build_corpus
    from topicexplorer.lib.chinese import modern_chinese_tokenizer
  File "/Users/colin/anaconda/lib/python3.6/site-packages/topicexplorer/lib/chinese.py", line 68, in <module>
    for a in string.lowercase[:],string.uppercase[:],range(0,10):
AttributeError: module 'string' has no attribute 'lowercase'

**Comment by colinallen** [comment]
Will need cleanup of chinese.py for Py3
