### ISSUE TITLE
update failing: no module named 'pip.utils'

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#304]
I updated pip and now have a problem with topicexplorer update:
```
colin% topicexplorer update
Traceback (most recent call last):
  File "/Users/colin/anaconda3/bin/topicexplorer", line 10, in <module>
    sys.exit(main())
  File "/Users/colin/corpora/topicexplorer/topicexplorer/__main__.py", line 260, in main
    benchmark(update.main)(args)
  File "/Users/colin/corpora/topicexplorer/topicexplorer/update.py", line 196, in main
    update(args)
  File "/Users/colin/corpora/topicexplorer/topicexplorer/update.py", line 64, in update
    from pip.utils import (get_installed_version, dist_is_editable, dist_location)
ModuleNotFoundError: No module named 'pip.utils'
```
Followed directions at https://askubuntu.com/questions/1025189/pip-is-not-working-importerror-no-module-named-pip-internal to force reinstallation of pip, but did not solve problem.

**Comment by JaimieMurdock** [comment]
output of `pip --version`?

**Comment by colinallen** [comment]
pip 10.0.1 from /Users/colin/anaconda3/lib/python3.6/site-packages/pip (python 3.6)

**Comment by colinallen** [comment]
Downgraded to pip 9.0.3, but that reverts to an error that caused me to do the update in the first place:
```
colin% topicexplorer update
You have an editable install, so updates will be pulled from git.
Your install directory is: /Users/colin/corpora/topicexplorer

Traceback (most recent call last):
  File "/Users/colin/anaconda3/bin/topicexplorer", line 10, in <module>
    sys.exit(main())
  File "/Users/colin/corpora/topicexplorer/topicexplorer/__main__.py", line 260, in main
    benchmark(update.main)(args)
  File "/Users/colin/corpora/topicexplorer/topicexplorer/update.py", line 196, in main
    update(args)
  File "/Users/colin/corpora/topicexplorer/topicexplorer/update.py", line 111, in update
    if repo.active_branch != repo.heads.master:
  File "/Users/colin/anaconda3/lib/python3.6/site-packages/git/repo/base.py", line 267, in heads
    return Head.list_items(self)
  File "/Users/colin/anaconda3/lib/python3.6/site-packages/git/util.py", line 942, in list_items
    out_list.extend(cls.iter_items(repo, *args, **kwargs))
  File "/Users/colin/anaconda3/lib/python3.6/site-packages/git/refs/symbolic.py", line 609, in _iter_items
    for sha, rela_path in cls._iter_packed_refs(repo):  # @UnusedVariable
  File "/Users/colin/anaconda3/lib/python3.6/site-packages/git/refs/symbolic.py", line 100, in _iter_packed_refs
    raise TypeError("PackingType of packed-Refs not understood: %r" % line)
TypeError: PackingType of packed-Refs not understood: '# pack-refs with: peeled fully-peeled sorted'

```

**Comment by JaimieMurdock** [comment]
Alright - so there's definitely an issue with `topicexplorer update` and editable installs.

The quick workarounds are:
**developer install** -- `python setup.py develop`
**default install** -- `pip install topicexplorer==1.0b204`

**Comment by JaimieMurdock** [comment]
https://mail.python.org/pipermail/distutils-sig/2017-October/031642.html

**Comment by JaimieMurdock** [comment]
Fortunately this was an easy quick patch. `pip.utils` -> `pip._internal.utils.misc`

obfuscation for no real purpose other than freeing up maintenance headaches later...
