### ISSUE TITLE
Deployment missing templates

### ISSUE THREAD

**Issue by JaimieMurdock** [inpho/topic-explorer#68]
```python
127.0.0.1 - - [24/Apr/2015 14:22:55] "GET /icons.js HTTP/1.1" 500 749
Traceback (most recent call last):
  File "/Users/colin/anaconda/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Users/colin/anaconda/bin/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/Users/colin/anaconda/lib/python2.7/site-packages/topicexplorer/server.py", line 265, in index
    encoding='utf-8') as tmpl_file:
  File "/Users/colin/anaconda/lib/python2.7/codecs.py", line 878, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: '/Users/colin/anaconda/lib/python2.7/site-packages/topicexplorer/../www/index.mustache.html'
127.0.0.1 - - [24/Apr/2015 14:22:57] "GET /?doc=1995_It_isnt_what_you_think-_a_new_idea_about_i.txt HTTP/1.1" 500 797
8020
Loading LDA data from /Users/colin/corpora/models/c_allen-nltk-en-freq5-LDA-K20-document-200.npz


```

**Comment by JaimieMurdock** [comment]
Issue was closed in 1.0b11
