### ISSUE TITLE
color map bug affecting browser launch

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#89]
I trained up some models (k=5,10) on Xiahong’s papers and everything seems to run fine, including loading the basic notebook — but vsm launch fails, and it seems to have something to do with the color mapping.  The 10 model is being served, but the 5 model fails.  Here’s the log output:

topic_colors =  [(n, bmap.mpl_colormap(color / float(ncolors-1))) for n,color in colors.iteritems()]
UnboundLocalError: local variable 'colors' referenced before assignment
Loading LDA data from /Users/colin/corpora/Chinese/XW/models/XWPapers-freq5-freq5-N1500-LDA-K5-document-400.npz
Traceback (most recent call last):
  File "/Users/colin/anaconda/bin/vsm", line 9, in <module>
    load_entry_point('topicexplorer==1.0b32', 'console_scripts', 'vsm')()
  File "/Users/colin/corpora/Chinese/XW/src/topicexplorer/topicexplorer/__main__.py", line 82, in main
    server.main(args)
  File "/Users/colin/corpora/Chinese/XW/src/topicexplorer/topicexplorer/server.py", line 356, in main
    load_model(args.k)
  File "/Users/colin/corpora/Chinese/XW/src/topicexplorer/topicexplorer/server.py", line 354, in load_model
    colors = dict(get_topic_colors(lda_v))
  File "/Users/colin/corpora/Chinese/XW/src/topicexplorer/topicexplorer/lib/color.py", line 126, in get_topic_colors
    topic_colors =  [(n, bmap.mpl_colormap(color / float(ncolors-1))) for n,color in colors.iteritems()]
UnboundLocalError: local variable 'colors' referenced before assignment

I’ve tarred up the whole shebang (corpus and models) and attached to see whether you get the same problem. 
[XW.zip](https://github.com/inpho/topic-explorer/files/99221/XW.zip)

**Comment by JaimieMurdock** [comment]
Interesting! That has to do with the bug fix I put in last night for 
topic_colors, and it also failed it's build through Travis last night.

Should be able to look at 11 today - headed to campus right now.
