### ISSUE TITLE
vsm startup error: unknown locale UTF-8

### ISSUE THREAD

**Issue by wang39** [inpho/topic-explorer#90]
On Xiaohong's computer -- any attempt to run vsm (even just vsm -h) producing a locale error:

Traceback (most recent call last):
  File "/Users/wang/anaconda2/bin/vsm", line 9, in <module>
    load_entry_point('topicexplorer==1.0b28', 'console_scripts', 'vsm')()
  File "/Users/wang/anaconda2/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/Users/wang/anaconda2/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/pkg_resources/__init__.py", line 2697, in load_entry_point
  File "/Users/wang/anaconda2/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/pkg_resources/__init__.py", line 2370, in load
  File "/Users/wang/anaconda2/lib/python2.7/site-packages/setuptools-18.5-py2.7.egg/pkg_resources/__init__.py", line 2376, in resolve
  File "/Users/wang/src/topicexplorer/topicexplorer/__main__.py", line 7, in <module>
    from topicexplorer import init, prep, train, server, launch, notebook, demo
  File "/Users/wang/src/topicexplorer/topicexplorer/server.py", line 27, in <module>
    import topicexplorer.lib.color as colorlib
  File "/Users/wang/src/topicexplorer/topicexplorer/lib/color.py", line 1, in <module>
    import brewer2mpl as brewer
  File "/Users/wang/anaconda2/lib/python2.7/site-packages/brewer2mpl/__init__.py", line 7, in <module>
    from .brewer2mpl import *
  File "/Users/wang/anaconda2/lib/python2.7/site-packages/brewer2mpl/brewer2mpl.py", line 10, in <module>
    from matplotlib.colors import LinearSegmentedColormap
  File "/Users/wang/anaconda2/lib/python2.7/site-packages/matplotlib/__init__.py", line 1131, in <module>
    rcParams = rc_params()
  File "/Users/wang/anaconda2/lib/python2.7/site-packages/matplotlib/__init__.py", line 975, in rc_params
    return rc_params_from_file(fname, fail_on_error)
  File "/Users/wang/anaconda2/lib/python2.7/site-packages/matplotlib/__init__.py", line 1100, in rc_params_from_file
    config_from_file = _rc_params_in_file(fname, fail_on_error)
  File "/Users/wang/anaconda2/lib/python2.7/site-packages/matplotlib/__init__.py", line 1018, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/Users/wang/anaconda2/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/wang/anaconda2/lib/python2.7/site-packages/matplotlib/__init__.py", line 1000, in _open_file_or_url
    encoding = locale.getdefaultlocale()[1]
  File "/Users/wang/anaconda2/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/Users/wang/anaconda2/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

**Comment by JaimieMurdock** [comment]
Hi Xiaohong - which operating system are you using - Mac, Windows or Linux?
The locale seems strange - it should have something like "zn_CN.UTF-8".

**Comment by colinallen** [comment]
Hi Jaimie - She is using Mac OS. - Colin

On Jan 26, 2016, at 11:42 PM, Jaimie Murdock <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Xiaohong - which operating system are you using - Mac, Windows or Linux?
The locale seems strange - it should have something like "zn_CN.UTF-8".

**Comment by JaimieMurdock** [comment]
Somehow the LANG variable does not have a language and country set, just 
an encoding.

Add the following two lines to her ~/.bash_profile:

|export LC_ALL=zh_CN.UTF-8
export LANG=zh_CN.UTF-8|

**Comment by JaimieMurdock** [comment]
Was this fixed?

**Comment by colinallen** [comment]
I don’t know.  I need to write a message to Xiaohong so I will ask her.

On Feb 13, 2016, at 10:21 PM, Jaimie Murdock <notifications@github.com<mailto:notifications@github.com>> wrote:


Was this fixed?

**Comment by JaimieMurdock** [comment]
Closing due to inactivity.
